name: LiteNetheriteGrind
version: '1.1'
author: github.com/zKOSMOSz | www.spigotmc.org/members/chris_thecrafter.6124
website: github.com/zKOSMOSz/LiteNetheriteGrind
main: KOSMOS.LiteNetheriteGrind
api-version: '1.18'